# Generated by Django 3.2.9 on 2022-04-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FetchData', '0002_alter_patientdetails_bodytemp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=100)),
                ('DateTime', models.CharField(max_length=70)),
                ('OrderNum', models.CharField(max_length=10)),
            ],
        ),
    ]
